version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: ~/workspace

    steps:
      - checkout

      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Eslint
          command: npm run lint:ci

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit

  publish:
    docker:
      - image: cimg/node:lts

    steps:
      - add_ssh_keys
      - checkout

      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: master
            tags:
              only: /v.*/
      - publish:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
